### list all messages

GET http://localhost:3000/messages

### Create a new message

POST http://localhost:3000/messages
content-type: application/json

{
  "content": "Hello Abdullah!"
}

### Get a particular message

GET http://localhost:3000/messages/569

### Create a new user
POST http://localhost:3000/auth/signup
content-type: application/json

{
  "email": "abd1@gmail.com",
  "password": "vgvgv"
}

### Find a particular user with a given ID

GET http://localhost:3000/auth/5


### find a particul user with a given email

GET http://localhost:3000/auth?email=abd1@gmail.com

### delete a particular user with a given ID

DELETE http://localhost:3000/auth/4

### Update a particular user with a given ID

PATCH http://localhost:3000/auth/1
content-type: application/json

{
  "email": "aaa@gmail.com",
  "password": "123456"
}